### ISSUE TITLE
Creating Cluster and Deploying

### ISSUE THREAD

**Issue by Neth77-lang** [mcsid5397/Prvn-Repo#1]
How and why to do 
What is the need
@mcsid5397

**Comment by Neth77-lang** [comment]
Helllloo

**Comment by mcsid5397** [comment]
> How and why to do What is the need @mcsid5397

Creating cluster would let you in **deploying certain packages and stuffs**!... So, creating cluster is necessary.
While creating cluster make use of 
**kind create cluster --config <filename.yaml>**

Where the <filename.yaml> contains these contents...
![WhatsApp Image 2023-05-08 at 17 33 12](https://user-images.githubusercontent.com/64912029/236819014-6c7c7cbf-c80f-4edd-be1a-5def151c13a4.jpg)
